title: Arithran Thurairetnam
description: Nothing super crazy going on here, just info on stuff I build and things that annoy on a daily basis
copyright: Arithran Thurairetnam
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: arithran
facebook_username:
twitter_username: "arithran"
linkedin_username: "arithran"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "arithran"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
permalink: /:categories/:year/:month/:day/:title
